services:
    _defaults:
        autowire: true
        autoconfigure: true

    Alexanevsky\OutputNormalizerBundle\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection'
